/**
 * The Enlighten Systems API
 * The Enlighten Systems API is a JSON-based API that provides access to performance data for a PV system. By using the Enlighten Systems API, you agree to the Enphase Energy API License Agreement.  Please note that the Enlighten Systems API does not provide performance data at a panel or microinverter level.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Meta from './Meta';
import RgmStatsIntervals from './RgmStatsIntervals';
import RgmStatsMeterIntervals from './RgmStatsMeterIntervals';

/**
 * The RgmStats model module.
 * @module model/RgmStats
 * @version 2.0
 */
class RgmStats {
    /**
     * Constructs a new <code>RgmStats</code>.
     * @alias module:model/RgmStats
     * @param systemId {Number} Enlighten ID for this system.
     * @param totalDevices {Number} Number of active revenue-grade meters for this system.
     * @param meta {module:model/Meta} 
     * @param intervals {Array.<module:model/RgmStatsIntervals>} A list of intervals between the requested start and end times.
     * @param meterIntervals {Array.<module:model/RgmStatsMeterIntervals>} A list of intervals of a meter between the requested start and end times.
     */
    constructor(systemId, totalDevices, meta, intervals, meterIntervals) { 
        
        RgmStats.initialize(this, systemId, totalDevices, meta, intervals, meterIntervals);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, systemId, totalDevices, meta, intervals, meterIntervals) { 
        obj['system_id'] = systemId;
        obj['total_devices'] = totalDevices;
        obj['meta'] = meta;
        obj['intervals'] = intervals;
        obj['meter_intervals'] = meterIntervals;
    }

    /**
     * Constructs a <code>RgmStats</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RgmStats} obj Optional instance to populate.
     * @return {module:model/RgmStats} The populated <code>RgmStats</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RgmStats();

            if (data.hasOwnProperty('system_id')) {
                obj['system_id'] = ApiClient.convertToType(data['system_id'], 'Number');
            }
            if (data.hasOwnProperty('total_devices')) {
                obj['total_devices'] = ApiClient.convertToType(data['total_devices'], 'Number');
            }
            if (data.hasOwnProperty('meta')) {
                obj['meta'] = Meta.constructFromObject(data['meta']);
            }
            if (data.hasOwnProperty('intervals')) {
                obj['intervals'] = ApiClient.convertToType(data['intervals'], [RgmStatsIntervals]);
            }
            if (data.hasOwnProperty('meter_intervals')) {
                obj['meter_intervals'] = ApiClient.convertToType(data['meter_intervals'], [RgmStatsMeterIntervals]);
            }
        }
        return obj;
    }


}

/**
 * Enlighten ID for this system.
 * @member {Number} system_id
 */
RgmStats.prototype['system_id'] = undefined;

/**
 * Number of active revenue-grade meters for this system.
 * @member {Number} total_devices
 */
RgmStats.prototype['total_devices'] = undefined;

/**
 * @member {module:model/Meta} meta
 */
RgmStats.prototype['meta'] = undefined;

/**
 * A list of intervals between the requested start and end times.
 * @member {Array.<module:model/RgmStatsIntervals>} intervals
 */
RgmStats.prototype['intervals'] = undefined;

/**
 * A list of intervals of a meter between the requested start and end times.
 * @member {Array.<module:model/RgmStatsMeterIntervals>} meter_intervals
 */
RgmStats.prototype['meter_intervals'] = undefined;






export default RgmStats;

