/**
 * The Enphase Commissioning API
 * Commissioning API can be used to create and update activations on a site, manage companies and users, update Tariff, etc.
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetCompanyUsersResponseUsersInner from './GetCompanyUsersResponseUsersInner';

/**
 * The GetPvManufacturersResponse model module.
 * @module model/GetPvManufacturersResponse
 * @version 4.0
 */
class GetPvManufacturersResponse {
    /**
     * Constructs a new <code>GetPvManufacturersResponse</code>.
     * @alias module:model/GetPvManufacturersResponse
     */
    constructor() { 
        
        GetPvManufacturersResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetPvManufacturersResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetPvManufacturersResponse} obj Optional instance to populate.
     * @return {module:model/GetPvManufacturersResponse} The populated <code>GetPvManufacturersResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetPvManufacturersResponse();

            if (data.hasOwnProperty('pv_manufacturers')) {
                obj['pv_manufacturers'] = ApiClient.convertToType(data['pv_manufacturers'], [[GetCompanyUsersResponseUsersInner]]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetPvManufacturersResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetPvManufacturersResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['pv_manufacturers'])) {
            throw new Error("Expected the field `pv_manufacturers` to be an array in the JSON data but got " + data['pv_manufacturers']);
        }

        return true;
    }


}



/**
 * A list of PV manufacturers. Each element in the list is an array including the model's manufacturer's primary key and name. The list may be empty.
 * @member {Array.<Array.<module:model/GetCompanyUsersResponseUsersInner>>} pv_manufacturers
 */
GetPvManufacturersResponse.prototype['pv_manufacturers'] = undefined;






export default GetPvManufacturersResponse;

