/*
 * The Enphase Monitoring API
 *
 * Monitoring API can be used to fetch system details on a site, system-level production and consumption data, and device-level production data.
 *
 * The version of the OpenAPI document: 4.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EnphaseOpenAPI.Monitoring.Client.OpenAPIDateConverter;
using System.Reflection;

namespace EnphaseOpenAPI.Monitoring.Model
{
    /// <summary>
    /// GetSystems500Response
    /// </summary>
    [JsonConverter(typeof(GetSystems500ResponseJsonConverter))]
    [DataContract(Name = "GetSystems_500_response")]
    public partial class GetSystems500Response : AbstractOpenAPISchema, IEquatable<GetSystems500Response>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetSystems500Response" /> class
        /// with the <see cref="InternalServerError" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of InternalServerError.</param>
        public GetSystems500Response(InternalServerError actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GetSystems500Response" /> class
        /// with the <see cref="DataTemporarilyUnavailableError" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of DataTemporarilyUnavailableError.</param>
        public GetSystems500Response(DataTemporarilyUnavailableError actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(DataTemporarilyUnavailableError))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(InternalServerError))
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: DataTemporarilyUnavailableError, InternalServerError");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `InternalServerError`. If the actual instance is not `InternalServerError`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of InternalServerError</returns>
        public InternalServerError GetInternalServerError()
        {
            return (InternalServerError)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `DataTemporarilyUnavailableError`. If the actual instance is not `DataTemporarilyUnavailableError`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of DataTemporarilyUnavailableError</returns>
        public DataTemporarilyUnavailableError GetDataTemporarilyUnavailableError()
        {
            return (DataTemporarilyUnavailableError)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetSystems500Response {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, GetSystems500Response.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of GetSystems500Response
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of GetSystems500Response</returns>
        public static GetSystems500Response FromJson(string jsonString)
        {
            GetSystems500Response newGetSystems500Response = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newGetSystems500Response;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(DataTemporarilyUnavailableError).GetProperty("AdditionalProperties") == null)
                {
                    newGetSystems500Response = new GetSystems500Response(JsonConvert.DeserializeObject<DataTemporarilyUnavailableError>(jsonString, GetSystems500Response.SerializerSettings));
                }
                else
                {
                    newGetSystems500Response = new GetSystems500Response(JsonConvert.DeserializeObject<DataTemporarilyUnavailableError>(jsonString, GetSystems500Response.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("DataTemporarilyUnavailableError");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into DataTemporarilyUnavailableError: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(InternalServerError).GetProperty("AdditionalProperties") == null)
                {
                    newGetSystems500Response = new GetSystems500Response(JsonConvert.DeserializeObject<InternalServerError>(jsonString, GetSystems500Response.SerializerSettings));
                }
                else
                {
                    newGetSystems500Response = new GetSystems500Response(JsonConvert.DeserializeObject<InternalServerError>(jsonString, GetSystems500Response.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("InternalServerError");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into InternalServerError: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + matchedTypes);
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newGetSystems500Response;
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetSystems500Response);
        }

        /// <summary>
        /// Returns true if GetSystems500Response instances are equal
        /// </summary>
        /// <param name="input">Instance of GetSystems500Response to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetSystems500Response input)
        {
            if (input == null)
                return false;

            return this.ActualInstance.Equals(input.ActualInstance);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ActualInstance != null)
                    hashCode = hashCode * 59 + this.ActualInstance.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for GetSystems500Response
    /// </summary>
    public class GetSystems500ResponseJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(GetSystems500Response).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            if(reader.TokenType != JsonToken.Null)
            {
                return GetSystems500Response.FromJson(JObject.Load(reader).ToString(Formatting.None));
            }
            return null;
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
