/**
 * The Enphase Monitoring API
 * Monitoring API can be used to fetch system details on a site, system-level production and consumption data, and device-level production data.
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetSystemRgmStatsResponseIntervalsInner model module.
 * @module model/GetSystemRgmStatsResponseIntervalsInner
 * @version 4.0
 */
class GetSystemRgmStatsResponseIntervalsInner {
    /**
     * Constructs a new <code>GetSystemRgmStatsResponseIntervalsInner</code>.
     * @alias module:model/GetSystemRgmStatsResponseIntervalsInner
     */
    constructor() { 
        
        GetSystemRgmStatsResponseIntervalsInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetSystemRgmStatsResponseIntervalsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetSystemRgmStatsResponseIntervalsInner} obj Optional instance to populate.
     * @return {module:model/GetSystemRgmStatsResponseIntervalsInner} The populated <code>GetSystemRgmStatsResponseIntervalsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetSystemRgmStatsResponseIntervalsInner();

            if (data.hasOwnProperty('end_at')) {
                obj['end_at'] = ApiClient.convertToType(data['end_at'], 'Number');
            }
            if (data.hasOwnProperty('devices_reporting')) {
                obj['devices_reporting'] = ApiClient.convertToType(data['devices_reporting'], 'Number');
            }
            if (data.hasOwnProperty('wh_del')) {
                obj['wh_del'] = ApiClient.convertToType(data['wh_del'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetSystemRgmStatsResponseIntervalsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetSystemRgmStatsResponseIntervalsInner</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * End time of the telemetry interval.
 * @member {Number} end_at
 */
GetSystemRgmStatsResponseIntervalsInner.prototype['end_at'] = undefined;

/**
 * Number of revenue-grade meters that reported data for this interval at the time of the request.
 * @member {Number} devices_reporting
 */
GetSystemRgmStatsResponseIntervalsInner.prototype['devices_reporting'] = undefined;

/**
 * Energy delivered during this interval, in Wh.
 * @member {Number} wh_del
 */
GetSystemRgmStatsResponseIntervalsInner.prototype['wh_del'] = undefined;






export default GetSystemRgmStatsResponseIntervalsInner;

