/*
 * The Enlighten Systems API
 *
 * The Enlighten Systems API is a JSON-based API that provides access to performance data for a PV system. By using the Enlighten Systems API, you agree to the Enphase Energy API License Agreement.  Please note that the Enlighten Systems API does not provide performance data at a panel or microinverter level.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EnphaseOpenAPI.Enlighten.Api;
using EnphaseOpenAPI.Enlighten.Model;
using EnphaseOpenAPI.Enlighten.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EnphaseOpenAPI.Enlighten.Test.Model
{
    /// <summary>
    ///  Class for testing EnergyLifetimeResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EnergyLifetimeResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EnergyLifetimeResponse
        //private EnergyLifetimeResponse instance;

        public EnergyLifetimeResponseTests()
        {
            // TODO uncomment below to create an instance of EnergyLifetimeResponse
            //instance = new EnergyLifetimeResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EnergyLifetimeResponse
        /// </summary>
        [Fact]
        public void EnergyLifetimeResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" EnergyLifetimeResponse
            //Assert.IsType<EnergyLifetimeResponse>(instance);
        }


        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Fact]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'SystemId'
        /// </summary>
        [Fact]
        public void SystemIdTest()
        {
            // TODO unit test for the property 'SystemId'
        }
        /// <summary>
        /// Test the property 'Production'
        /// </summary>
        [Fact]
        public void ProductionTest()
        {
            // TODO unit test for the property 'Production'
        }
        /// <summary>
        /// Test the property 'MicroProduction'
        /// </summary>
        [Fact]
        public void MicroProductionTest()
        {
            // TODO unit test for the property 'MicroProduction'
        }
        /// <summary>
        /// Test the property 'MeterProduction'
        /// </summary>
        [Fact]
        public void MeterProductionTest()
        {
            // TODO unit test for the property 'MeterProduction'
        }
        /// <summary>
        /// Test the property 'MeterStartDate'
        /// </summary>
        [Fact]
        public void MeterStartDateTest()
        {
            // TODO unit test for the property 'MeterStartDate'
        }
        /// <summary>
        /// Test the property 'Meta'
        /// </summary>
        [Fact]
        public void MetaTest()
        {
            // TODO unit test for the property 'Meta'
        }

    }

}
