/*
 * The Enlighten Systems API
 *
 * The Enlighten Systems API is a JSON-based API that provides access to performance data for a PV system. By using the Enlighten Systems API, you agree to the Enphase Energy API License Agreement.  Please note that the Enlighten Systems API does not provide performance data at a panel or microinverter level.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EnphaseOpenAPI.Enlighten.Api;
using EnphaseOpenAPI.Enlighten.Model;
using EnphaseOpenAPI.Enlighten.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EnphaseOpenAPI.Enlighten.Test.Model
{
    /// <summary>
    ///  Class for testing InlineResponse2007Intervals1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse2007Intervals1Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2007Intervals1
        //private InlineResponse2007Intervals1 instance;

        public InlineResponse2007Intervals1Tests()
        {
            // TODO uncomment below to create an instance of InlineResponse2007Intervals1
            //instance = new InlineResponse2007Intervals1();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineResponse2007Intervals1
        /// </summary>
        [Fact]
        public void InlineResponse2007Intervals1InstanceTest()
        {
            // TODO uncomment below to test "IsType" InlineResponse2007Intervals1
            //Assert.IsType<InlineResponse2007Intervals1>(instance);
        }


        /// <summary>
        /// Test the property 'Channel'
        /// </summary>
        [Fact]
        public void ChannelTest()
        {
            // TODO unit test for the property 'Channel'
        }
        /// <summary>
        /// Test the property 'EndAt'
        /// </summary>
        [Fact]
        public void EndAtTest()
        {
            // TODO unit test for the property 'EndAt'
        }
        /// <summary>
        /// Test the property 'WhDel'
        /// </summary>
        [Fact]
        public void WhDelTest()
        {
            // TODO unit test for the property 'WhDel'
        }
        /// <summary>
        /// Test the property 'CurrW'
        /// </summary>
        [Fact]
        public void CurrWTest()
        {
            // TODO unit test for the property 'CurrW'
        }

    }

}
