/*
 * The Enlighten Systems API
 *
 * The Enlighten Systems API is a JSON-based API that provides access to performance data for a PV system. By using the Enlighten Systems API, you agree to the Enphase Energy API License Agreement.  Please note that the Enlighten Systems API does not provide performance data at a panel or microinverter level.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EnphaseOpenAPI.Enlighten.Api;
using EnphaseOpenAPI.Enlighten.Model;
using EnphaseOpenAPI.Enlighten.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EnphaseOpenAPI.Enlighten.Test.Model
{
    /// <summary>
    ///  Class for testing InlineResponse4XX
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse4XXTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineResponse4XX
        //private InlineResponse4XX instance;

        public InlineResponse4XXTests()
        {
            // TODO uncomment below to create an instance of InlineResponse4XX
            //instance = new InlineResponse4XX();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineResponse4XX
        /// </summary>
        [Fact]
        public void InlineResponse4XXInstanceTest()
        {
            // TODO uncomment below to test "IsType" InlineResponse4XX
            //Assert.IsType<InlineResponse4XX>(instance);
        }


        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Fact]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

    }

}
