/*
 * The Enlighten Systems API
 *
 * The Enlighten Systems API is a JSON-based API that provides access to performance data for a PV system. By using the Enlighten Systems API, you agree to the Enphase Energy API License Agreement.  Please note that the Enlighten Systems API does not provide performance data at a panel or microinverter level.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EnphaseOpenAPI.Enlighten.Api;
using EnphaseOpenAPI.Enlighten.Model;
using EnphaseOpenAPI.Enlighten.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EnphaseOpenAPI.Enlighten.Test.Model
{
    /// <summary>
    ///  Class for testing ServerError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServerErrorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServerError
        //private ServerError instance;

        public ServerErrorTests()
        {
            // TODO uncomment below to create an instance of ServerError
            //instance = new ServerError();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServerError
        /// </summary>
        [Fact]
        public void ServerErrorInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServerError
            //Assert.IsType<ServerError>(instance);
        }


        /// <summary>
        /// Test the property 'ErrorCode'
        /// </summary>
        [Fact]
        public void ErrorCodeTest()
        {
            // TODO unit test for the property 'ErrorCode'
        }
        /// <summary>
        /// Test the property 'ErrorMessages'
        /// </summary>
        [Fact]
        public void ErrorMessagesTest()
        {
            // TODO unit test for the property 'ErrorMessages'
        }

    }

}
