/*
The Enphase Monitoring API

Monitoring API can be used to fetch system details on a site, system-level production and consumption data, and device-level production data.

API version: 4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package monitoring

import (
	"encoding/json"
)

// checks if the GetSystemRgmStatsResponseIntervalsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSystemRgmStatsResponseIntervalsInner{}

// GetSystemRgmStatsResponseIntervalsInner struct for GetSystemRgmStatsResponseIntervalsInner
type GetSystemRgmStatsResponseIntervalsInner struct {
	// End time of the telemetry interval.
	EndAt *int64 `json:"end_at,omitempty"`
	// Number of revenue-grade meters that reported data for this interval at the time of the request.
	DevicesReporting *int32 `json:"devices_reporting,omitempty"`
	// Energy delivered during this interval, in Wh.
	WhDel *int32 `json:"wh_del,omitempty"`
}

// NewGetSystemRgmStatsResponseIntervalsInner instantiates a new GetSystemRgmStatsResponseIntervalsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSystemRgmStatsResponseIntervalsInner() *GetSystemRgmStatsResponseIntervalsInner {
	this := GetSystemRgmStatsResponseIntervalsInner{}
	return &this
}

// NewGetSystemRgmStatsResponseIntervalsInnerWithDefaults instantiates a new GetSystemRgmStatsResponseIntervalsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSystemRgmStatsResponseIntervalsInnerWithDefaults() *GetSystemRgmStatsResponseIntervalsInner {
	this := GetSystemRgmStatsResponseIntervalsInner{}
	return &this
}

// GetEndAt returns the EndAt field value if set, zero value otherwise.
func (o *GetSystemRgmStatsResponseIntervalsInner) GetEndAt() int64 {
	if o == nil || IsNil(o.EndAt) {
		var ret int64
		return ret
	}
	return *o.EndAt
}

// GetEndAtOk returns a tuple with the EndAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSystemRgmStatsResponseIntervalsInner) GetEndAtOk() (*int64, bool) {
	if o == nil || IsNil(o.EndAt) {
		return nil, false
	}
	return o.EndAt, true
}

// HasEndAt returns a boolean if a field has been set.
func (o *GetSystemRgmStatsResponseIntervalsInner) HasEndAt() bool {
	if o != nil && !IsNil(o.EndAt) {
		return true
	}

	return false
}

// SetEndAt gets a reference to the given int64 and assigns it to the EndAt field.
func (o *GetSystemRgmStatsResponseIntervalsInner) SetEndAt(v int64) {
	o.EndAt = &v
}

// GetDevicesReporting returns the DevicesReporting field value if set, zero value otherwise.
func (o *GetSystemRgmStatsResponseIntervalsInner) GetDevicesReporting() int32 {
	if o == nil || IsNil(o.DevicesReporting) {
		var ret int32
		return ret
	}
	return *o.DevicesReporting
}

// GetDevicesReportingOk returns a tuple with the DevicesReporting field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSystemRgmStatsResponseIntervalsInner) GetDevicesReportingOk() (*int32, bool) {
	if o == nil || IsNil(o.DevicesReporting) {
		return nil, false
	}
	return o.DevicesReporting, true
}

// HasDevicesReporting returns a boolean if a field has been set.
func (o *GetSystemRgmStatsResponseIntervalsInner) HasDevicesReporting() bool {
	if o != nil && !IsNil(o.DevicesReporting) {
		return true
	}

	return false
}

// SetDevicesReporting gets a reference to the given int32 and assigns it to the DevicesReporting field.
func (o *GetSystemRgmStatsResponseIntervalsInner) SetDevicesReporting(v int32) {
	o.DevicesReporting = &v
}

// GetWhDel returns the WhDel field value if set, zero value otherwise.
func (o *GetSystemRgmStatsResponseIntervalsInner) GetWhDel() int32 {
	if o == nil || IsNil(o.WhDel) {
		var ret int32
		return ret
	}
	return *o.WhDel
}

// GetWhDelOk returns a tuple with the WhDel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSystemRgmStatsResponseIntervalsInner) GetWhDelOk() (*int32, bool) {
	if o == nil || IsNil(o.WhDel) {
		return nil, false
	}
	return o.WhDel, true
}

// HasWhDel returns a boolean if a field has been set.
func (o *GetSystemRgmStatsResponseIntervalsInner) HasWhDel() bool {
	if o != nil && !IsNil(o.WhDel) {
		return true
	}

	return false
}

// SetWhDel gets a reference to the given int32 and assigns it to the WhDel field.
func (o *GetSystemRgmStatsResponseIntervalsInner) SetWhDel(v int32) {
	o.WhDel = &v
}

func (o GetSystemRgmStatsResponseIntervalsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSystemRgmStatsResponseIntervalsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EndAt) {
		toSerialize["end_at"] = o.EndAt
	}
	if !IsNil(o.DevicesReporting) {
		toSerialize["devices_reporting"] = o.DevicesReporting
	}
	if !IsNil(o.WhDel) {
		toSerialize["wh_del"] = o.WhDel
	}
	return toSerialize, nil
}

type NullableGetSystemRgmStatsResponseIntervalsInner struct {
	value *GetSystemRgmStatsResponseIntervalsInner
	isSet bool
}

func (v NullableGetSystemRgmStatsResponseIntervalsInner) Get() *GetSystemRgmStatsResponseIntervalsInner {
	return v.value
}

func (v *NullableGetSystemRgmStatsResponseIntervalsInner) Set(val *GetSystemRgmStatsResponseIntervalsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSystemRgmStatsResponseIntervalsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSystemRgmStatsResponseIntervalsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSystemRgmStatsResponseIntervalsInner(val *GetSystemRgmStatsResponseIntervalsInner) *NullableGetSystemRgmStatsResponseIntervalsInner {
	return &NullableGetSystemRgmStatsResponseIntervalsInner{value: val, isSet: true}
}

func (v NullableGetSystemRgmStatsResponseIntervalsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSystemRgmStatsResponseIntervalsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


